apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: conector-gemini:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: default
spec:
  selector:
    app: python-api
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "myresolver"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - conector.docker.localhost
    secretName: python-api-tls
  rules:
  - host: conector.docker.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-api
            port:
              number: 80