services:
  database:
    image: mysql:8.0
    container_name: database_tiendas_don_pepe
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - app-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      DATABASE_HOST: ${HOST_DATABASE_API}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
    depends_on:
      - database
    ports:
      - "${API_PORT}:${API_PORT}"
    restart: always
    networks:
      - app-network
    command: npm run start:prod

networks:
  app-network:
    driver: bridge
